### ISSUE TITLE
Support for HTML5

### ISSUE THREAD

**Issue by Numczi** [fivefingergames/TwitchAuth#27]
Is it possible to customize the plugin for HTML5?
After compilation I have such errors.

UATHelper: Packaging (HTML5):   LogInit: Display: LogClass: Warning: BoolProperty FTwitchSubscription::is_gift is not initialized properly
UATHelper: Packaging (HTML5):   LogInit: Display: LogClass: Warning: BoolProperty FTwitchChannel::mature is not initialized properly
UATHelper: Packaging (HTML5):   LogInit: Display: LogClass: Warning: BoolProperty FTwitchChannel::partner is not initialized properly
UATHelper: Packaging (HTML5):   LogInit: Display: LogClass: Warning: FTwitchChannel::views is not initialized properly
UATHelper: Packaging (HTML5):   LogInit: Display: LogClass: Warning: FTwitchChannel::followers is not initialized properly
UATHelper: Packaging (HTML5):   LogInit: Display: LogClass: Warning: BoolProperty FTwitchFollow::notifications is not initialized properly
UATHelper: Packaging (HTML5):   LogInit: Display: LogClass: Warning: FTwitchError::status is not initialized properly
UATHelper: Packaging (HTML5):   LogInit: Display: LogClass: Warning: BoolProperty FTwitchUser::email_verified is not initialized properly
UATHelper: Packaging (HTML5):   LogInit: Display: LogClass: Warning: BoolProperty FTwitchUser::partnered is not initialized properly
UATHelper: Packaging (HTML5):   LogInit: Display: LogClass: Warning: BoolProperty FTwitchUser::twitter_connected is not initialized properly
UATHelper: Packaging (HTML5):   LogInit: Display: LogClass: Warning: BoolProperty FTwitchUserNotifications::push is not initialized properly
UATHelper: Packaging (HTML5):   LogInit: Display: LogClass: Warning: BoolProperty FTwitchUserNotifications::email is not initialized properly
UATHelper: Packaging (HTML5):   LogInit: Display: LogAutomationTest: Warning: BoolProperty FTwitchSubscription::is_gift is not initialized properly
UATHelper: Packaging (HTML5):   LogInit: Display: LogAutomationTest: Warning: BoolProperty FTwitchChannel::mature is not initialized properly
UATHelper: Packaging (HTML5):   LogInit: Display: LogAutomationTest: Warning: BoolProperty FTwitchChannel::partner is not initialized properly
UATHelper: Packaging (HTML5):   LogInit: Display: LogAutomationTest: Warning: FTwitchChannel::views is not initialized properly
UATHelper: Packaging (HTML5):   LogInit: Display: LogAutomationTest: Warning: FTwitchChannel::followers is not initialized properly
UATHelper: Packaging (HTML5):   LogInit: Display: LogAutomationTest: Warning: BoolProperty FTwitchFollow::notifications is not initialized properly
UATHelper: Packaging (HTML5):   LogInit: Display: LogAutomationTest: Warning: FTwitchError::status is not initialized properly
UATHelper: Packaging (HTML5):   LogInit: Display: LogAutomationTest: Warning: BoolProperty FTwitchUser::email_verified is not initialized properly
UATHelper: Packaging (HTML5):   LogInit: Display: LogAutomationTest: Warning: BoolProperty FTwitchUser::partnered is not initialized properly
UATHelper: Packaging (HTML5):   LogInit: Display: LogAutomationTest: Warning: BoolProperty FTwitchUser::twitter_connected is not initialized properly
UATHelper: Packaging (HTML5):   LogInit: Display: LogAutomationTest: Warning: BoolProperty FTwitchUserNotifications::push is not initialized properly
UATHelper: Packaging (HTML5):   LogInit: Display: LogAutomationTest: Warning: BoolProperty FTwitchUserNotifications::email is not initialized properly

**Comment by mrbandler** [comment]
Hi @Numczi, thank you for reporting and sorry for the late response. 

It seems that Epic changed the UAT tool to spit out some warnings, that weren't there before. On what version of UE4 did you try to compile?

**Comment by Numczi** [comment]
UE 4.22 but in Windows compile, everything works fine, the only problem is with HTML5, I think this is too much work because the Web Browser Widget is also not supported by HTML5.

**Comment by mrbandler** [comment]
I think we can close this as HTML5 support has been dropped bty Epic Games all together.
