### ISSUE TITLE
Twitch login not work

### ISSUE THREAD

**Issue by naginder14** [fivefingergames/TwitchAuth#28]
Hi, 
 I am using this git hub code and also purchased plugin twitch authentication, but my after login it show server error.

1 ) I also register the app on twitch account.
2) added client ID

But I cant able to login.Please help me out.

**Comment by mrbandler** [comment]
Hi @naginder14,

what does the server error say?

**Comment by naginder14** [comment]
Hi,
Thanks for your response.
 It shows this error.
Failed to load URL
http://localhost:3000/auth/twitch/callback?error=redirect_mismatch&error_description=Parameter+redirect_uri+does+not+match+registered+URI
with error ERR_CONNECTION_REFUSED (-102).

1) I had only added the client ID and then run the project.

**Comment by naginder14** [comment]
Thanks for the response.
I had remove the saved directory completely after closing the project, but it doesn't work for me.

**Comment by naginder14** [comment]
what is subscription call back method in the code, because after Login it shows a "Nope" in subscription part.
please suggest what steps I missing in this?

**Comment by mrbandler** [comment]
Did you change the Twitch user to check the subscription for in the example project?

If not it makes sense that you get a "Nope" because you probably not subscribed to my put in example Twitch user.

**Comment by naginder14** [comment]
Yes, I have not change anything in example. So please suggest where  I have to change in same...?

Also, suggest me one more thing, can we twitch authentication in native browser like (open in Google chrome etc) and redirects to application continue.
